--
-- PostgreSQL database dump
--

\restrict Lg0nUpnU5Fomi3Z7m3iOJdixp66O3B44Ij6P04HZOXlWtxd3gCkYfRZoPG7axND

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: app_custodytransferlog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_custodytransferlog (
    id bigint NOT NULL,
    device_asset_id character varying(50) NOT NULL,
    from_user_name character varying(150) NOT NULL,
    from_emp_id character varying(50) NOT NULL,
    to_user_name character varying(150) NOT NULL,
    to_emp_id character varying(50) NOT NULL,
    handover_date character varying(50) NOT NULL,
    assigned_by character varying(100) NOT NULL,
    remarks text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    device_id bigint
);


ALTER TABLE public.app_custodytransferlog OWNER TO postgres;

--
-- Name: app_custodytransferlog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_custodytransferlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_custodytransferlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_deviceasset; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_deviceasset (
    id bigint NOT NULL,
    dev_id character varying(50) NOT NULL,
    asset_id character varying(50) NOT NULL,
    serial_number character varying(100) NOT NULL,
    org_id character varying(20) NOT NULL,
    org_name character varying(100) NOT NULL,
    building_name character varying(100) NOT NULL,
    floor_name character varying(100) NOT NULL,
    room_name character varying(100) NOT NULL,
    assigned_user_id character varying(50),
    assigned_user_name character varying(150) NOT NULL,
    assigned_emp_id character varying(50) NOT NULL,
    monitor_spec character varying(255) NOT NULL,
    cpu_processor character varying(255) NOT NULL,
    storage_ram character varying(255) NOT NULL,
    ip_address character varying(50) NOT NULL,
    mac_address character varying(50) NOT NULL,
    operating_system character varying(100) NOT NULL,
    purchase_date character varying(50) NOT NULL,
    warranty_expiry_date character varying(50) NOT NULL,
    status character varying(30) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    device_type character varying(100) NOT NULL,
    assigned_designation character varying(150) NOT NULL,
    assigned_email character varying(150) NOT NULL,
    assigned_phone character varying(50) NOT NULL,
    keyboard_spec character varying(255) NOT NULL,
    mouse_spec character varying(255) NOT NULL,
    printer_spec character varying(255) NOT NULL,
    tablet_spec character varying(255) NOT NULL,
    ups_spec character varying(255) NOT NULL,
    assigned_department character varying(150) NOT NULL,
    brand_name character varying(100) NOT NULL,
    anydesk_id character varying(100) NOT NULL,
    device_id character varying(100) NOT NULL
);


ALTER TABLE public.app_deviceasset OWNER TO postgres;

--
-- Name: app_deviceasset_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_deviceasset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_deviceasset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_devicecomplaint; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_devicecomplaint (
    id bigint NOT NULL,
    ticket_id character varying(30) NOT NULL,
    user_full_name character varying(150) NOT NULL,
    emp_id character varying(50) NOT NULL,
    user_email character varying(150) NOT NULL,
    user_dept character varying(100) NOT NULL,
    org_id character varying(20) NOT NULL,
    device_asset_id character varying(50) NOT NULL,
    room_location character varying(100) NOT NULL,
    issue_category character varying(100) NOT NULL,
    priority character varying(30) NOT NULL,
    subject character varying(200) NOT NULL,
    description text NOT NULL,
    status character varying(30) NOT NULL,
    admin_remarks text NOT NULL,
    technician_name character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    user_id integer
);


ALTER TABLE public.app_devicecomplaint OWNER TO postgres;

--
-- Name: app_devicecomplaint_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_devicecomplaint ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_devicecomplaint_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_equipmentbreakdown; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_equipmentbreakdown (
    id bigint NOT NULL,
    breakdown_date character varying(50) NOT NULL,
    breakdown_time character varying(50) NOT NULL,
    asset_id character varying(100) NOT NULL,
    device_name character varying(100) NOT NULL,
    breakdown_cause text NOT NULL,
    equipment_type character varying(50) NOT NULL,
    intimation_datetime character varying(100) NOT NULL,
    checkin_datetime character varying(100) NOT NULL,
    dept_hod_name character varying(150) NOT NULL,
    it_staff_name character varying(150) NOT NULL,
    repair_datetime character varying(100) NOT NULL,
    tat_duration character varying(100) NOT NULL,
    sign_dept_hod character varying(150) NOT NULL,
    sign_it_cell character varying(150) NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    location character varying(150) NOT NULL
);


ALTER TABLE public.app_equipmentbreakdown OWNER TO postgres;

--
-- Name: app_equipmentbreakdown_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_equipmentbreakdown ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_equipmentbreakdown_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_equipmentpms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_equipmentpms (
    id bigint NOT NULL,
    equipment_name character varying(150) NOT NULL,
    company_name character varying(100) NOT NULL,
    installation_date character varying(50) NOT NULL,
    asset_code character varying(100) NOT NULL,
    maintenance_frequency character varying(50) NOT NULL,
    pms1_done_date character varying(50) NOT NULL,
    pms2_due_date character varying(50) NOT NULL,
    pms2_done_date character varying(50) NOT NULL,
    pms3_due_date character varying(50) NOT NULL,
    pms3_done_date character varying(50) NOT NULL,
    pms4_due_date character varying(50) NOT NULL,
    pms4_done_date character varying(50) NOT NULL,
    status character varying(50) NOT NULL,
    department_location character varying(150) NOT NULL,
    engineer_notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.app_equipmentpms OWNER TO postgres;

--
-- Name: app_equipmentpms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_equipmentpms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_equipmentpms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_userprofile (
    id bigint NOT NULL,
    emp_id character varying(50) NOT NULL,
    full_name character varying(150) NOT NULL,
    org_id character varying(20) NOT NULL,
    department character varying(100) NOT NULL,
    designation character varying(100) NOT NULL,
    phone character varying(20) NOT NULL,
    assigned_asset_id character varying(50) NOT NULL,
    user_id integer NOT NULL,
    password character varying(150) NOT NULL
);


ALTER TABLE public.app_userprofile OWNER TO postgres;

--
-- Name: app_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Data for Name: app_custodytransferlog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_custodytransferlog (id, device_asset_id, from_user_name, from_emp_id, to_user_name, to_emp_id, handover_date, assigned_by, remarks, created_at, device_id) FROM stdin;
\.


--
-- Data for Name: app_deviceasset; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_deviceasset (id, dev_id, asset_id, serial_number, org_id, org_name, building_name, floor_name, room_name, assigned_user_id, assigned_user_name, assigned_emp_id, monitor_spec, cpu_processor, storage_ram, ip_address, mac_address, operating_system, purchase_date, warranty_expiry_date, status, created_at, updated_at, device_type, assigned_designation, assigned_email, assigned_phone, keyboard_spec, mouse_spec, printer_spec, tablet_spec, ups_spec, assigned_department, brand_name, anydesk_id, device_id) FROM stdin;
22	dev-6a33bacd	PSM/IT/0826/002	SN-PSM-DIS-7921	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	1		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.734472+05:30	2026-09-28 10:03:41.734486+05:30	Display									Pharmacy	Dell		
23	dev-ba61e73b	PSM/IT/0826/002	SN-PSM-CPU-5192	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	1		Unassigned			i7-6700T	8/256	192.168.33.184			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.741963+05:30	2026-09-28 10:03:41.742+05:30	CPU									Pharmacy	HP		
170	dev-330f7c0c	PSM/IT/0926/001	SN-PSM-CPU-8992	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	202		Unassigned		24" FHD IPS Display	i5	8/256	192.168.0.130		Windows 11 Pro	28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:22:41.54601+05:30	2026-09-28 10:22:41.546022+05:30	CPU									FMW	Intex		
171	dev-d86cb66f	PSM/IT/0926/001	SN-PSM-DIS-9569	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	202		Unassigned		24" FHD IPS Display	24" FHD IPS Display		-	-		28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:22:41.547154+05:30	2026-09-28 10:22:41.547161+05:30	Display									FMW	Zebronics		
20	dev-a642da6f	PSM/IT/0826/001	SN-TEST-DISP-001	HOSP	PSM Hospital	PSM Hospital	2nd Floor	1		Unassigned		24 inch Full HD	24 inch Full HD		-	-		28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.722283+05:30	2026-09-28 10:17:01.776541+05:30	Display										Dell		
21	dev-888cd3fa	PSM/IT/0826/001	SN-TEST-CPU-001	HOSP	PSM Hospital	PSM Hospital	2nd Floor	1		Unassigned		24 inch Full HD	Intel Core i5-11400	16GB RAM / 512GB SSD			Windows 11 Pro	28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.730069+05:30	2026-09-28 10:17:01.775614+05:30	CPU										HP		
24	dev-b14bc926	PSM/IT/0826/003	SN-PSM-DIS-9488	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	1		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.74868+05:30	2026-09-28 10:03:41.748695+05:30	Display									Pharmacy	Dell		
25	dev-972c2b44	PSM/IT/0826/003	SN-PSM-CPU-3768	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	1		Unassigned			i5-6500T	8/256	192.168.88.174			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.752807+05:30	2026-09-28 10:03:41.752853+05:30	CPU									Pharmacy	HP		
26	dev-60e1a626	PSM/IT/0826/004	SN-PSM-DIS-1403	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	1		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.761173+05:30	2026-09-28 10:03:41.761199+05:30	Display									Pharmacy	LG		
27	dev-9affcaf9	PSM/IT/0826/004	SN-PSM-CPU-6745	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	1		Unassigned			i5-7500	8/256	192.168.88.169			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.767285+05:30	2026-09-28 10:03:41.767299+05:30	CPU									Pharmacy	Dell		
29	dev-dc0a6a1d	PSM/IT/0826/005	SN-PSM-CPU-8061	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	1		Unassigned			i5-7500	4/256	192.168.88.190			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.775589+05:30	2026-09-28 10:03:41.775607+05:30	CPU									Pharmacy	Dell		
28	dev-42b0635a	PSM/IT/0826/005	SN-PSM-DIS-1496	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	1		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.771336+05:30	2026-09-28 10:03:41.771349+05:30	Display									Pharmacy	LG		
30	dev-b02a32d3	PSM/IT/0826/006	SN-PSM-DIS-3622	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	1		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.779802+05:30	2026-09-28 10:03:41.779816+05:30	Display									Pharmacy	Zebronics		
31	dev-1232502d	PSM/IT/0826/006	SN-PSM-CPU-6946	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	1		Unassigned			i7-6700T	8/256	192.168.88.237			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.783439+05:30	2026-09-28 10:03:41.783451+05:30	CPU									Pharmacy	Intex		
33	dev-febc96db	PSM/IT/0826/007	SN-PSM-CPU-007	HOSP	PSM Hospital	PSM Hospital	2nd Floor	2		Unassigned		24" FHD IPS Display	Intel i5	16GB RAM / 512GB SSD			Windows 11 Pro	28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.792181+05:30	2026-09-28 10:44:11.964976+05:30	CPU										HP		
32	dev-44011751	PSM/IT/0826/007	SN-PSM-DISP-007	HOSP	PSM Hospital	PSM Hospital	2nd Floor	2		Unassigned		24" FHD IPS Display	24" FHD IPS Display		-	-		28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.787441+05:30	2026-09-28 10:44:11.969766+05:30	Display												
34	dev-05f01efe	PSM/IT/0826/008	SN-PSM-DIS-7958	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	3		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.796511+05:30	2026-09-28 10:03:41.796525+05:30	Display									Cardio	Zebronics		
35	dev-914ff74e	PSM/IT/0826/008	SN-PSM-CPU-7150	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	3		Unassigned			i3-8100	8/256	192.168.31.209			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.800405+05:30	2026-09-28 10:03:41.800425+05:30	CPU									Cardio	Intex		
36	dev-9553c85e	PSM/IT/0826/009	SN-PSM-DIS-4732	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	4		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.805147+05:30	2026-09-28 10:03:41.805161+05:30	Display									Pediatric	Zebronics		
37	dev-704ef12e	PSM/IT/0826/009	SN-PSM-CPU-5112	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	4		Unassigned			i3-8100	8/256				28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.809777+05:30	2026-09-28 10:03:41.809814+05:30	CPU									Pediatric	Intex		
39	dev-cfefa2a2	PSM/IT/0826/010	SN-PSM-CPU-3917	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	10		Unassigned			i3-8100	8/256				28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.818227+05:30	2026-09-28 10:03:41.818243+05:30	CPU									Ortho OPD	Intex		
38	dev-7b1f030d	PSM/IT/0826/010	SN-PSM-DIS-5627	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	10		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.814077+05:30	2026-09-28 10:03:41.814092+05:30	Display									Ortho OPD	Zebronics		
40	dev-975033dd	PSM/IT/0826/011	SN-PSM-DIS-8987	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	13		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.821955+05:30	2026-09-28 10:03:41.821969+05:30	Display									Medicine	Zebronics		
41	dev-dc905128	PSM/IT/0826/011	SN-PSM-CPU-5090	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	13		Unassigned			i3-8100	8/256	192.168.251.100			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.826712+05:30	2026-09-28 10:03:41.826729+05:30	CPU									Medicine	Intex		
42	dev-476526a3	PSM/IT/0826/012	SN-PSM-DIS-2319	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	14		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.831237+05:30	2026-09-28 10:03:41.83125+05:30	Display									Gyenic	Zebronics		
43	dev-f550c343	PSM/IT/0826/012	SN-PSM-CPU-9703	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	14		Unassigned			i3-8100	8/256	192.168.31.204			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.835165+05:30	2026-09-28 10:03:41.83518+05:30	CPU									Gyenic	Intex		
44	dev-6f4472f7	PSM/IT/0826/013	SN-PSM-DIS-6194	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-1		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.839138+05:30	2026-09-28 10:03:41.839152+05:30	Display									Reception	Zebronics		
45	dev-a696b0d5	PSM/IT/0826/013	SN-PSM-CPU-2697	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-1		Unassigned			i5	4/120/520	192.168.38.34			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.843427+05:30	2026-09-28 10:03:41.843449+05:30	CPU									Reception	Dell		
46	dev-0e0327c6	PSM/IT/0826/014	SN-PSM-DIS-3270	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-2		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.847377+05:30	2026-09-28 10:03:41.847391+05:30	Display									Reception	Krystaa		
47	dev-911c73af	PSM/IT/0826/014	SN-PSM-CPU-7726	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-2		Unassigned			i5	8/256	192.168.38.112			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.851281+05:30	2026-09-28 10:03:41.851294+05:30	CPU									Reception	Intex		
49	dev-dc9b5f41	PSM/IT/0826/015	SN-PSM-CPU-8060	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-3		Unassigned			i5	8/256	192.168.88.223			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.859849+05:30	2026-09-28 10:03:41.859862+05:30	CPU									Reception	HP		
48	dev-26f5325e	PSM/IT/0826/015	SN-PSM-DIS-5002	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-3		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.855138+05:30	2026-09-28 10:03:41.855153+05:30	Display									Reception	Krystaa		
50	dev-d4782f8e	PSM/IT/0826/016	SN-PSM-DIS-3216	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-4		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.864056+05:30	2026-09-28 10:03:41.864071+05:30	Display									Reception	Samsung		
51	dev-240b88dd	PSM/IT/0826/016	SN-PSM-CPU-9177	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-4		Unassigned			i5	8/240	192.168.38.118			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.869935+05:30	2026-09-28 10:03:41.86995+05:30	CPU									Reception	HP		
52	dev-35a74b02	PSM/IT/0826/017	SN-PSM-DIS-7282	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-5		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.874236+05:30	2026-09-28 10:03:41.874249+05:30	Display									Reception	Nanotech		
53	dev-16500371	PSM/IT/0826/017	SN-PSM-CPU-8959	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-5		Unassigned			i5	8/240	192.168.8.14			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.878482+05:30	2026-09-28 10:03:41.878495+05:30	CPU									Reception	HP		
55	dev-cb3888ea	PSM/IT/0826/018	SN-PSM-CPU-3094	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-6		Unassigned			i5	8/256	192.168.32.195			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.886166+05:30	2026-09-28 10:03:41.886179+05:30	CPU									Reception	HP		
54	dev-86f198a7	PSM/IT/0826/018	SN-PSM-DIS-3386	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-6		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.882483+05:30	2026-09-28 10:03:41.882496+05:30	Display									Reception	Nanotech		
56	dev-53498515	PSM/IT/0826/019	SN-PSM-DIS-3536	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-7		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.890328+05:30	2026-09-28 10:03:41.890341+05:30	Display									Reception	Dell		
57	dev-c13c234d	PSM/IT/0826/019	SN-PSM-CPU-4414	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-7		Unassigned			i5	8/240	192.168.88.245			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.895269+05:30	2026-09-28 10:03:41.895283+05:30	CPU									Reception	HP		
58	dev-bf27965c	PSM/IT/0826/020	SN-PSM-DIS-2440	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-8		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.899352+05:30	2026-09-28 10:03:41.899365+05:30	Display									Reception	Dell		
59	dev-b7bf2764	PSM/IT/0826/020	SN-PSM-CPU-3144	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-8		Unassigned			i5	8/256	192.168.88.124			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.903394+05:30	2026-09-28 10:03:41.903408+05:30	CPU									Reception	HP		
60	dev-1222d9b4	PSM/IT/0826/021	SN-PSM-DIS-4406	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-9		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.907203+05:30	2026-09-28 10:03:41.907215+05:30	Display									Reception	Dell		
61	dev-9ed570e7	PSM/IT/0826/021	SN-PSM-CPU-9834	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-9		Unassigned			i5	8/256	192.168.8.157			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.912207+05:30	2026-09-28 10:03:41.912221+05:30	CPU									Reception	HP		
62	dev-76845cca	PSM/IT/0826/022	SN-PSM-DIS-5545	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-10		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.916066+05:30	2026-09-28 10:03:41.916082+05:30	Display									Reception	Dell		
63	dev-6df3ddbf	PSM/IT/0826/022	SN-PSM-CPU-4508	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	16/Window-10		Unassigned			i5	8/240	192.168.32.64			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.919668+05:30	2026-09-28 10:03:41.919681+05:30	CPU									Reception	HP		
64	dev-92ae3b51	PSM/IT/0826/023	SN-PSM-DIS-7739	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/CT MRI		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.923823+05:30	2026-09-28 10:03:41.923863+05:30	Display									Rediology	Zebster		
65	dev-3053af60	PSM/IT/0826/023	SN-PSM-CPU-3790	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/CT MRI		Unassigned			i5-6400	8/256	192.168.9.33			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.929164+05:30	2026-09-28 10:03:41.929178+05:30	CPU									Rediology	Dell		
66	dev-9feac38d	PSM/IT/0826/024	SN-PSM-DIS-5229	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/USG-1		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.933383+05:30	2026-09-28 10:03:41.933399+05:30	Display									Rediology	LG		
67	dev-2a54e09a	PSM/IT/0826/024	SN-PSM-CPU-5693	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/USG-1		Unassigned			i5-7500T	8/256	192.168.31.223			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.937019+05:30	2026-09-28 10:03:41.937034+05:30	CPU									Rediology	Intex		
68	dev-6a152273	PSM/IT/0826/025	SN-PSM-DIS-9904	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/USG-1		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.941187+05:30	2026-09-28 10:03:41.941208+05:30	Display									Rediology	Dell		
69	dev-b09ece28	PSM/IT/0826/025	SN-PSM-CPU-5038	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/USG-1		Unassigned			i7-6700T	8/256	192.168.33.152			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.945737+05:30	2026-09-28 10:03:41.94575+05:30	CPU									Rediology	HP		
70	dev-46279dd0	PSM/IT/0826/026	SN-PSM-DIS-2523	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/USG-2		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.949736+05:30	2026-09-28 10:03:41.949749+05:30	Display									Rediology	Dell		
71	dev-fab140a4	PSM/IT/0826/026	SN-PSM-CPU-9836	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/USG-2		Unassigned			i5-6500T	8/256	192.168.9.55			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.953706+05:30	2026-09-28 10:03:41.953718+05:30	CPU									Rediology	HP		
72	dev-95b80857	PSM/IT/0826/027	SN-PSM-DIS-1470	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/USG-2		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.95768+05:30	2026-09-28 10:03:41.957693+05:30	Display									Rediology	Zebronics		
73	dev-7dcdb43b	PSM/IT/0826/027	SN-PSM-CPU-3930	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/USG-2		Unassigned			i5-12500	16/2TB	192.168.9.40			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.961907+05:30	2026-09-28 10:03:41.96192+05:30	CPU									Rediology	HP		
74	dev-9e67be54	PSM/IT/0826/028	SN-PSM-DIS-1008	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/Dr. Room		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.965206+05:30	2026-09-28 10:03:41.965219+05:30	Display									Rediology	Zebronics		
75	dev-ee2c0d9d	PSM/IT/0826/028	SN-PSM-CPU-1589	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/Dr. Room		Unassigned			i5	8/256	192.168.31.226			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.969101+05:30	2026-09-28 10:03:41.969115+05:30	CPU									Rediology	HP		
76	dev-f05f4fcd	PSM/IT/0826/029	SN-PSM-DIS-3391	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/Redio Reception		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.973532+05:30	2026-09-28 10:03:41.973545+05:30	Display									Rediology	Krystaa		
77	dev-c1eb4d5d	PSM/IT/0826/029	SN-PSM-CPU-3514	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/Redio Reception		Unassigned			i3-8100	8/256	192.168.32.152			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.978553+05:30	2026-09-28 10:03:41.978568+05:30	CPU									Rediology	Intex		
78	dev-a340e129	PSM/IT/0826/030	SN-PSM-DIS-9190	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/RSO		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.9829+05:30	2026-09-28 10:03:41.982914+05:30	Display									Rediology	Zebronics		
79	dev-616b3139	PSM/IT/0826/030	SN-PSM-CPU-8403	HOSP	PSM Hospital	PSM Hospital Main Complex	GROUND FLOOR	17/RSO		Unassigned			i3-8100	8/256	192.168.32.217			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.98677+05:30	2026-09-28 10:03:41.986782+05:30	CPU									Rediology	Intex		
80	dev-057e15a7	PSM/IT/0826/031	SN-PSM-DIS-1845	HOSP	PSM Hospital	PSM Hospital Main Complex	1ST FLOOR	101		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.991125+05:30	2026-09-28 10:03:41.99114+05:30	Display									Ophthalmology	Zebronics		
81	dev-741b6248	PSM/IT/0826/031	SN-PSM-CPU-1023	HOSP	PSM Hospital	PSM Hospital Main Complex	1ST FLOOR	101		Unassigned			i3-8100	8/256				28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:41.995841+05:30	2026-09-28 10:03:41.995854+05:30	CPU									Ophthalmology	Intex		
82	dev-239e24ff	PSM/IT/0826/032	SN-PSM-DIS-7432	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	102		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.00007+05:30	2026-09-28 10:03:42.000085+05:30	Display									ENT	Zebronics		
83	dev-12da68f6	PSM/IT/0826/032	SN-PSM-CPU-5561	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	102		Unassigned			i3-8100	8/256	192.168.11.206			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.004783+05:30	2026-09-28 10:03:42.004796+05:30	CPU									ENT	Intex		
84	dev-5f51f5c9	PSM/IT/0826/033	SN-PSM-DIS-6890	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Blood Reception-1		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.011173+05:30	2026-09-28 10:03:42.011186+05:30	Display									Center Lab	Dell		
85	dev-ad8d2e0c	PSM/IT/0826/033	SN-PSM-CPU-8831	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Blood Reception-1		Unassigned			i5	8/256	192.168.8.151			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.014929+05:30	2026-09-28 10:03:42.014941+05:30	CPU									Center Lab	HP		
86	dev-ac721ede	PSM/IT/0826/034	SN-PSM-DIS-5168	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Blood Reception-2		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.018945+05:30	2026-09-28 10:03:42.01897+05:30	Display									Center Lab	Dell		
87	dev-7de1fa0a	PSM/IT/0826/034	SN-PSM-CPU-5043	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Blood Reception-2		Unassigned			i7-6700T	8/256	192.168.11.198			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.023272+05:30	2026-09-28 10:03:42.023286+05:30	CPU									Center Lab	HP		
88	dev-3180ec41	PSM/IT/0826/035	SN-PSM-DIS-8731	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Blood Lab Test		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.028246+05:30	2026-09-28 10:03:42.02826+05:30	Display									Center Lab	HCL		
89	dev-eb2e3105	PSM/IT/0826/035	SN-PSM-CPU-4626	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Blood Lab Test		Unassigned			i5	16/256/1TB	192.168.33.235			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.032296+05:30	2026-09-28 10:03:42.032308+05:30	CPU									Center Lab	HP		
91	dev-863fcc88	PSM/IT/0826/036	SN-PSM-CPU-8310	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Cabin-3		Unassigned			i5	8/256	192.168.8.241			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.039645+05:30	2026-09-28 10:03:42.039657+05:30	CPU									Center Lab	HP		
90	dev-fd2056a0	PSM/IT/0826/036	SN-PSM-DIS-9350	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Cabin-3		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.036258+05:30	2026-09-28 10:03:42.036271+05:30	Display									Center Lab	LG		
92	dev-8645a3e3	PSM/IT/0826/037	SN-PSM-DIS-4433	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Cabin-1		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.04441+05:30	2026-09-28 10:03:42.044429+05:30	Display									Center Lab	LG		
93	dev-9890b8d2	PSM/IT/0826/037	SN-PSM-CPU-9676	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Cabin-1		Unassigned			i5	8/256	192.168.32.216			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.052041+05:30	2026-09-28 10:03:42.05206+05:30	CPU									Center Lab	HP		
94	dev-16f80945	PSM/IT/0826/038	SN-PSM-DIS-3108	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Cabin-2		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.056853+05:30	2026-09-28 10:03:42.056873+05:30	Display									Center Lab	LG		
95	dev-743c1770	PSM/IT/0826/038	SN-PSM-CPU-6306	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Cabin-2		Unassigned			i5	8/256	192.168.33.228			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.061796+05:30	2026-09-28 10:03:42.061813+05:30	CPU									Center Lab	Intex		
97	dev-0ccf15c3	PSM/IT/0826/039	SN-PSM-CPU-1892	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Blood Lab Test		Unassigned				8/256	192.168.8.138			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.071949+05:30	2026-09-28 10:03:42.071963+05:30	CPU									Center Lab	HP		
96	dev-6453f324	PSM/IT/0826/039	SN-PSM-DIS-7431	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Blood Lab Test		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.067284+05:30	2026-09-28 10:03:42.067306+05:30	Display									Center Lab	Dell		
98	dev-8f361bfc	PSM/IT/0826/040	SN-PSM-DIS-4022	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Cabin-5		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.077465+05:30	2026-09-28 10:03:42.077486+05:30	Display									Center Lab	Krystaa		
99	dev-e4175e8d	PSM/IT/0826/040	SN-PSM-CPU-3512	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Cabin-5		Unassigned			i3-8100	8/256	192.168.32.167			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.082959+05:30	2026-09-28 10:03:42.082974+05:30	CPU									Center Lab	Intex		
101	dev-913c94da	PSM/IT/0826/041	SN-PSM-CPU-1382	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Cabin-6		Unassigned			i5	8/256	192.168.32.166			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.093782+05:30	2026-09-28 10:03:42.093803+05:30	CPU									Center Lab	Intex		
100	dev-332ba5ed	PSM/IT/0826/041	SN-PSM-DIS-1241	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	103/Cabin-6		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.087381+05:30	2026-09-28 10:03:42.087394+05:30	Display									Center Lab	Krystaa		
103	dev-271127b1	PSM/IT/0826/042	SN-PSM-CPU-8604	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	104		Unassigned			i5	8/256				28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.104305+05:30	2026-09-28 10:03:42.104322+05:30	CPU									Dental	HP		
102	dev-72a6da08	PSM/IT/0826/042	SN-PSM-DIS-8905	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	104		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.099674+05:30	2026-09-28 10:03:42.09969+05:30	Display									Dental	Zebronics		
104	dev-8eb40c19	PSM/IT/0826/043	SN-PSM-DIS-9856	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	106		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.11136+05:30	2026-09-28 10:03:42.111384+05:30	Display									Pedia	Zebronics		
105	dev-d27516d6	PSM/IT/0826/043	SN-PSM-CPU-6528	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	106		Unassigned			i3-8100	8/256				28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.116728+05:30	2026-09-28 10:03:42.116742+05:30	CPU									Pedia	Intex		
106	dev-cb27d97a	PSM/IT/0826/044	SN-PSM-DIS-5722	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	110		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.121504+05:30	2026-09-28 10:03:42.121522+05:30	Display									NICU	Zebronics		
107	dev-7047f0ca	PSM/IT/0826/044	SN-PSM-CPU-2985	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	110		Unassigned			i3-8100	8/256				28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.126637+05:30	2026-09-28 10:03:42.126652+05:30	CPU									NICU	Intex		
108	dev-0b8d64fa	PSM/IT/0826/045	SN-PSM-DIS-9219	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	115		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.131594+05:30	2026-09-28 10:03:42.13162+05:30	Display									Ortho	Zebronics		
109	dev-d0224560	PSM/IT/0826/045	SN-PSM-CPU-3206	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	115		Unassigned			i3-8100	8/256				28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.135718+05:30	2026-09-28 10:03:42.135731+05:30	CPU									Ortho	Intex		
110	dev-89f4164a	PSM/IT/0826/046	SN-PSM-DIS-9053	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	116		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.139637+05:30	2026-09-28 10:03:42.139649+05:30	Display									NS Office	Zebronics		
111	dev-1eaf1dae	PSM/IT/0826/046	SN-PSM-CPU-2552	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	116		Unassigned			i7-6700T	8/240	192.168.31.102			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.144162+05:30	2026-09-28 10:03:42.144187+05:30	CPU									NS Office	Intex		
112	dev-2125cf1b	PSM/IT/0826/047	SN-PSM-DIS-9384	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	116		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.148445+05:30	2026-09-28 10:03:42.148458+05:30	Display									NS Office	Krystaa		
113	dev-cd7d66ea	PSM/IT/0826/047	SN-PSM-CPU-4755	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	116		Unassigned			i5	8/256	192.168.31.116			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.151973+05:30	2026-09-28 10:03:42.151986+05:30	CPU									NS Office	Intex		
114	dev-9a55e073	PSM/IT/0826/048	SN-PSM-DIS-6306	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	116		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.156357+05:30	2026-09-28 10:03:42.156369+05:30	Display									NS Office	Nanotech		
115	dev-b5fe8713	PSM/IT/0826/048	SN-PSM-CPU-4369	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	116		Unassigned			i5	8/256	192.168.31.181			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.161161+05:30	2026-09-28 10:03:42.161178+05:30	CPU									NS Office	HP		
116	dev-ce1fafb0	PSM/IT/0826/049	SN-PSM-DIS-9685	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	117/Cabin-1		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.165298+05:30	2026-09-28 10:03:42.165312+05:30	Display									Psychatry OPD	Zebronics		
117	dev-e0434c30	PSM/IT/0826/049	SN-PSM-CPU-2812	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	117/Cabin-1		Unassigned			i3-8100	8/256	192.168.31.213			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.168847+05:30	2026-09-28 10:03:42.16886+05:30	CPU									Psychatry OPD	Intex		
118	dev-23f4e0bc	PSM/IT/0826/050	SN-PSM-DIS-4967	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	117/Cabin-2		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.172707+05:30	2026-09-28 10:03:42.17272+05:30	Display									Dermatology OPD	Zebronics		
119	dev-ab7832de	PSM/IT/0826/050	SN-PSM-CPU-6354	HOSP	PSM Hospital	PSM Hospital Main Complex	1st FLOOR	117/Cabin-2		Unassigned			i3-8100	8/256	192.168.32.191			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.177003+05:30	2026-09-28 10:03:42.177022+05:30	CPU									Dermatology OPD	Intex		
120	dev-be98f04b	PSM/IT/0826/051	SN-PSM-DIS-9569	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	202		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.181223+05:30	2026-09-28 10:03:42.181237+05:30	Display									FMW	Zebronics		
121	dev-c3fc427c	PSM/IT/0826/051	SN-PSM-CPU-8992	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	202		Unassigned			i5	8/256	192.168.0.130			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.185671+05:30	2026-09-28 10:03:42.185687+05:30	CPU									FMW	Intex		
122	dev-ae5f41f4	PSM/IT/0826/052	SN-PSM-DIS-4890	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	205		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.190182+05:30	2026-09-28 10:03:42.190196+05:30	Display									Store Room	Dell		
123	dev-7627ed58	PSM/IT/0826/052	SN-PSM-CPU-3026	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	205		Unassigned			i5-6500T	8/256	192.168.88.226			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.195385+05:30	2026-09-28 10:03:42.195408+05:30	CPU									Store Room	HP		
124	dev-9ddf7938	PSM/IT/0826/053	SN-PSM-DIS-5357	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	209		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.200504+05:30	2026-09-28 10:03:42.200524+05:30	Display									Male Medicine	Zebronics		
125	dev-49e1d6e9	PSM/IT/0826/053	SN-PSM-CPU-2917	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	209		Unassigned			i5	8/256	192.168.0.168			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.205257+05:30	2026-09-28 10:03:42.205275+05:30	CPU									Male Medicine	Intex		
126	dev-e2174708	PSM/IT/0826/054	SN-PSM-DIS-4454	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	213		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.209758+05:30	2026-09-28 10:03:42.209773+05:30	Display									HDU	Zebronics		
127	dev-baa4d271	PSM/IT/0826/054	SN-PSM-CPU-5200	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	213		Unassigned			i5	8/256	192.168.32.109			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.214151+05:30	2026-09-28 10:03:42.214165+05:30	CPU									HDU	Intex		
128	dev-0abb2bd1	PSM/IT/0826/055	SN-PSM-DIS-6840	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	216		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.217858+05:30	2026-09-28 10:03:42.217871+05:30	Display									OBY Gyenic	Zebronics		
129	dev-8e795d5f	PSM/IT/0826/055	SN-PSM-CPU-9469	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	216		Unassigned			i5	8/256	192.168.32.208			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.22199+05:30	2026-09-28 10:03:42.222005+05:30	CPU									OBY Gyenic	Intex		
131	dev-2030e356	PSM/IT/0826/056	SN-PSM-CPU-2857	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	221		Unassigned			i5	8/256	192.168.31.232			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.232283+05:30	2026-09-28 10:03:42.232304+05:30	CPU									Admin	Intex		
130	dev-30027f72	PSM/IT/0826/056	SN-PSM-DIS-7487	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	221		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.226936+05:30	2026-09-28 10:03:42.226958+05:30	Display									Admin	Zebronics		
132	dev-08dbd039	PSM/IT/0826/057	SN-PSM-DIS-1983	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	221		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.237+05:30	2026-09-28 10:03:42.237015+05:30	Display									Admin	Zebronics		
133	dev-4834a84a	PSM/IT/0826/057	SN-PSM-CPU-7222	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	221		Unassigned			i5	8/256	192.168.31.108			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.241753+05:30	2026-09-28 10:03:42.24178+05:30	CPU									Admin	Intex		
134	dev-11654cc0	PSM/IT/0826/058	SN-PSM-DIS-3691	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	221		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.24609+05:30	2026-09-28 10:03:42.246103+05:30	Display									Admin	Zebronics		
135	dev-c6bd241c	PSM/IT/0826/058	SN-PSM-CPU-8739	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	221		Unassigned			i5	8/256	192.168.88.176			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.24982+05:30	2026-09-28 10:03:42.249833+05:30	CPU									Admin	HP		
136	dev-ebb175cc	PSM/IT/0826/059	SN-PSM-DIS-6370	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	221		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.253426+05:30	2026-09-28 10:03:42.253438+05:30	Display									Admin	Zebronics		
137	dev-b7c1dc41	PSM/IT/0826/059	SN-PSM-CPU-1578	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	221		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.257311+05:30	2026-09-28 10:03:42.257326+05:30	CPU									Admin	HP		
138	dev-9acf40ed	PSM/IT/0826/060	SN-PSM-DIS-5567	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	221		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.262014+05:30	2026-09-28 10:03:42.262028+05:30	Display									Admin	Zebronics		
139	dev-980fa498	PSM/IT/0826/060	SN-PSM-CPU-5509	HOSP	PSM Hospital	PSM Hospital Main Complex	2nd FLOOR	221		Unassigned			i5-6500	8/256	192.168.11.213			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.265851+05:30	2026-09-28 10:03:42.265864+05:30	CPU									Admin	HP		
140	dev-15895611	PSM/IT/0826/061	SN-PSM-DIS-4297	HOSP	PSM Hospital	PSM Hospital Main Complex	3rd FLOOR	307		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.269988+05:30	2026-09-28 10:03:42.270002+05:30	Display									Surgery Ward	Zebronics		
141	dev-f2f12528	PSM/IT/0826/061	SN-PSM-CPU-1995	HOSP	PSM Hospital	PSM Hospital Main Complex	3rd FLOOR	307		Unassigned			i5	8/240				28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.273864+05:30	2026-09-28 10:03:42.273876+05:30	CPU									Surgery Ward	Intex		
142	dev-ca981069	PSM/IT/0826/062	SN-PSM-DIS-8071	HOSP	PSM Hospital	PSM Hospital Main Complex	3rd FLOOR	318		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.278523+05:30	2026-09-28 10:03:42.278539+05:30	Display									IT Cell	Zebronics		
143	dev-6353d419	PSM/IT/0826/062	SN-PSM-CPU-4543	HOSP	PSM Hospital	PSM Hospital Main Complex	3rd FLOOR	318		Unassigned			i5	8/240	192.168.8.106			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.282365+05:30	2026-09-28 10:03:42.282377+05:30	CPU									IT Cell	Intex		
144	dev-6b1ddd27	PSM/IT/0826/063	SN-PSM-DIS-5104	HOSP	PSM Hospital	PSM Hospital Main Complex	3rd FLOOR	318		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.28598+05:30	2026-09-28 10:03:42.285995+05:30	Display									IT Cell	Zebronics		
145	dev-0a5d1a6f	PSM/IT/0826/063	SN-PSM-CPU-7065	HOSP	PSM Hospital	PSM Hospital Main Complex	3rd FLOOR	318		Unassigned			i5	8/240	192.168.31.238			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.289803+05:30	2026-09-28 10:03:42.289816+05:30	CPU									IT Cell	Intex		
146	dev-1796bdb4	PSM/IT/0826/064	SN-PSM-DIS-9929	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	401		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.29432+05:30	2026-09-28 10:03:42.294341+05:30	Display									MRD	Zebronics		
147	dev-4ded6d09	PSM/IT/0826/064	SN-PSM-CPU-5795	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	401		Unassigned			i5-6500T	8/256	192.168.32.206			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.298572+05:30	2026-09-28 10:03:42.298586+05:30	CPU									MRD	HP		
148	dev-9fb16ec0	PSM/IT/0826/065	SN-PSM-DIS-6034	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	401		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.302173+05:30	2026-09-28 10:03:42.302186+05:30	Display									MRD	Nanotech		
149	dev-6e90a50d	PSM/IT/0826/065	SN-PSM-CPU-3398	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	401		Unassigned			i5-6500T	8/256	192.168.32.106			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.306202+05:30	2026-09-28 10:03:42.306218+05:30	CPU									MRD	HP		
150	dev-5110df68	PSM/IT/0826/066	SN-PSM-DIS-7814	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	401		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.310833+05:30	2026-09-28 10:03:42.310851+05:30	Display									MRD	Nanotech		
151	dev-251ccd70	PSM/IT/0826/066	SN-PSM-CPU-5797	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	401		Unassigned			i5-6500T	8/256	192.168.32.238			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.314824+05:30	2026-09-28 10:03:42.314837+05:30	CPU									MRD	HP		
152	dev-e8e67bea	PSM/IT/0826/067	SN-PSM-DIS-5614	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	401		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.318512+05:30	2026-09-28 10:03:42.318524+05:30	Display									MRD	Nanotech		
153	dev-7e383030	PSM/IT/0826/067	SN-PSM-CPU-8899	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	401		Unassigned			i5-6500T	8/256	192.168.33.159			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.322667+05:30	2026-09-28 10:03:42.322682+05:30	CPU									MRD	HP		
154	dev-31439288	PSM/IT/0826/068	SN-PSM-DIS-1468	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	401		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.327752+05:30	2026-09-28 10:03:42.327768+05:30	Display									MRD	Nanotech		
155	dev-5edc5c75	PSM/IT/0826/068	SN-PSM-CPU-7206	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	401		Unassigned			i5-6500T	8/240	192.168.32.174			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.331892+05:30	2026-09-28 10:03:42.331905+05:30	CPU									MRD	HP		
156	dev-ae8a8599	PSM/IT/0826/069	SN-PSM-DIS-5999	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	402		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.335569+05:30	2026-09-28 10:03:42.335581+05:30	Display									MRD-2	ACER		
157	dev-a2905205	PSM/IT/0826/069	SN-PSM-CPU-2810	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	402		Unassigned			i5-6500	8/256	192.168.31.183			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.339755+05:30	2026-09-28 10:03:42.339769+05:30	CPU									MRD-2	HP		
158	dev-627253d6	PSM/IT/0826/070	SN-PSM-DIS-2659	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	404		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.34407+05:30	2026-09-28 10:03:42.344085+05:30	Display									Blood Bank	Zebronics		
159	dev-e2f8c5cb	PSM/IT/0826/070	SN-PSM-CPU-3134	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	404		Unassigned			i5-6500	8/256				28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.348467+05:30	2026-09-28 10:03:42.34848+05:30	CPU									Blood Bank	Intex		
160	dev-d252d7a3	PSM/IT/0826/071	SN-PSM-DIS-9857	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	410		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.352506+05:30	2026-09-28 10:03:42.35252+05:30	Display									SICU	Zebronics		
161	dev-b38bb284	PSM/IT/0826/071	SN-PSM-CPU-4784	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	410		Unassigned			i5-6500T	8/256	192.168.126.14			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.356342+05:30	2026-09-28 10:03:42.356354+05:30	CPU									SICU	Intex		
162	dev-057d36a6	PSM/IT/0826/072	SN-PSM-DIS-6697	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	411		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.360748+05:30	2026-09-28 10:03:42.360762+05:30	Display									ICU	Zebronics		
163	dev-500ee78e	PSM/IT/0826/072	SN-PSM-CPU-4189	HOSP	PSM Hospital	PSM Hospital Main Complex	4th FLOOR	411		Unassigned			i5-6500T	8/256	192.168.0.127			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.366321+05:30	2026-09-28 10:03:42.366335+05:30	CPU									ICU	Intex		
164	dev-fee69c4f	PSM/IT/0826/073	SN-PSM-DIS-2193	HOSP	PSM Hospital	PSM Hospital Main Complex	5th FLOOR	501		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.370446+05:30	2026-09-28 10:03:42.370459+05:30	Display									Anaesthesia Dep	Zebronics		
165	dev-39e5a090	PSM/IT/0826/073	SN-PSM-CPU-9111	HOSP	PSM Hospital	PSM Hospital Main Complex	5th FLOOR	501		Unassigned			i5-6500T	8/256	192.168.31.125			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.374229+05:30	2026-09-28 10:03:42.374242+05:30	CPU									Anaesthesia Dep	Intex		
167	dev-fc03dff5	PSM/IT/0826/074	SN-PSM-CPU-4961	HOSP	PSM Hospital	PSM Hospital Main Complex	5th FLOOR	501		Unassigned			i5-6500T	8/256	192.168.33.196			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.382978+05:30	2026-09-28 10:03:42.382993+05:30	CPU									OT	HP		
166	dev-14a7e106	PSM/IT/0826/074	SN-PSM-DIS-1356	HOSP	PSM Hospital	PSM Hospital Main Complex	5th FLOOR	501		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.378953+05:30	2026-09-28 10:03:42.378993+05:30	Display									OT	Dell		
168	dev-e74d816e	PSM/IT/0826/075	SN-PSM-DIS-5923	HOSP	PSM Hospital	PSM Hospital Main Complex	5th FLOOR	501		Unassigned								28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.38754+05:30	2026-09-28 10:03:42.387553+05:30	Display									Cath Lab	Krystaa		
169	dev-ae5a6991	PSM/IT/0826/075	SN-PSM-CPU-1207	HOSP	PSM Hospital	PSM Hospital Main Complex	5th FLOOR	501		Unassigned			i3-8100	8/256	192.168.33.168			28-Sep-2026	27-Sep-2029	Active	2026-09-28 10:03:42.391246+05:30	2026-09-28 10:03:42.391258+05:30	CPU									Cath Lab	Intex		
\.


--
-- Data for Name: app_devicecomplaint; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_devicecomplaint (id, ticket_id, user_full_name, emp_id, user_email, user_dept, org_id, device_asset_id, room_location, issue_category, priority, subject, description, status, admin_remarks, technician_name, created_at, updated_at, resolved_at, user_id) FROM stdin;
\.


--
-- Data for Name: app_equipmentbreakdown; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_equipmentbreakdown (id, breakdown_date, breakdown_time, asset_id, device_name, breakdown_cause, equipment_type, intimation_datetime, checkin_datetime, dept_hod_name, it_staff_name, repair_datetime, tat_duration, sign_dept_hod, sign_it_cell, status, created_at, updated_at, location) FROM stdin;
\.


--
-- Data for Name: app_equipmentpms; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_equipmentpms (id, equipment_name, company_name, installation_date, asset_code, maintenance_frequency, pms1_done_date, pms2_due_date, pms2_done_date, pms3_due_date, pms3_done_date, pms4_due_date, pms4_done_date, status, department_location, engineer_notes, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: app_userprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.app_userprofile (id, emp_id, full_name, org_id, department, designation, phone, assigned_asset_id, user_id, password) FROM stdin;
19	ADMIN	System Administrator	HOSP	IT & Medical Systems	Master Administrator			2	admin
21	KRI	krish patel	HOSP	IT & Medical Systems	Systems Administrator			20	admin123
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add device complaint	9	add_devicecomplaint
26	Can change device complaint	9	change_devicecomplaint
27	Can delete device complaint	9	delete_devicecomplaint
28	Can view device complaint	9	view_devicecomplaint
29	Can add user profile	10	add_userprofile
30	Can change user profile	10	change_userprofile
31	Can delete user profile	10	delete_userprofile
32	Can view user profile	10	view_userprofile
33	Can add device asset	8	add_deviceasset
34	Can change device asset	8	change_deviceasset
35	Can delete device asset	8	delete_deviceasset
36	Can view device asset	8	view_deviceasset
37	Can add custody transfer log	7	add_custodytransferlog
38	Can change custody transfer log	7	change_custodytransferlog
39	Can delete custody transfer log	7	delete_custodytransferlog
40	Can view custody transfer log	7	view_custodytransferlog
41	Can add Equipment PMS Record	11	add_equipmentpms
42	Can change Equipment PMS Record	11	change_equipmentpms
43	Can delete Equipment PMS Record	11	delete_equipmentpms
44	Can view Equipment PMS Record	11	view_equipmentpms
45	Can add Equipment Breakdown	12	add_equipmentbreakdown
46	Can change Equipment Breakdown	12	change_equipmentbreakdown
47	Can delete Equipment Breakdown	12	delete_equipmentbreakdown
48	Can view Equipment Breakdown	12	view_equipmentbreakdown
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
20	pbkdf2_sha256$1500000$klklXauJLfr2DtNh5ntBMl$ka5C6XFrnJYseJckm+0e0xQzG0SE93YrItI+FN3a+9I=	2026-09-25 14:51:08.46726+05:30	f	kri	krish	patel	krish2282003@gmail.com	t	t	2026-09-23 10:53:51.860431+05:30
2	pbkdf2_sha256$1500000$A8CyMaXjD88SbchpmAcFpK$kYKu8sjp3qGU12LQ9yLP2t9c9LDv+jeT55iKoxNC22Q=	2026-09-25 10:16:02.794938+05:30	t	admin	System	Administrator	admin@psmhospital.org	t	t	2026-09-07 14:31:28.221+05:30
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	app	custodytransferlog
8	app	deviceasset
9	app	devicecomplaint
10	app	userprofile
11	app	equipmentpms
12	app	equipmentbreakdown
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-07 14:29:04.290578+05:30
2	auth	0001_initial	2026-09-07 14:29:04.364329+05:30
3	admin	0001_initial	2026-09-07 14:29:04.382467+05:30
4	admin	0002_logentry_remove_auto_add	2026-09-07 14:29:04.387905+05:30
5	admin	0003_logentry_add_action_flag_choices	2026-09-07 14:29:04.392233+05:30
6	app	0001_initial	2026-09-07 14:29:04.425339+05:30
7	app	0002_deviceasset_custodytransferlog	2026-09-07 14:29:04.447287+05:30
8	contenttypes	0002_remove_content_type_name	2026-09-07 14:29:04.460927+05:30
9	auth	0002_alter_permission_name_max_length	2026-09-07 14:29:04.468736+05:30
10	auth	0003_alter_user_email_max_length	2026-09-07 14:29:04.476233+05:30
11	auth	0004_alter_user_username_opts	2026-09-07 14:29:04.481671+05:30
12	auth	0005_alter_user_last_login_null	2026-09-07 14:29:04.48787+05:30
13	auth	0006_require_contenttypes_0002	2026-09-07 14:29:04.489713+05:30
14	auth	0007_alter_validators_add_error_messages	2026-09-07 14:29:04.501304+05:30
15	auth	0008_alter_user_username_max_length	2026-09-07 14:29:04.512968+05:30
16	auth	0009_alter_user_last_name_max_length	2026-09-07 14:29:04.520526+05:30
17	auth	0010_alter_group_name_max_length	2026-09-07 14:29:04.52945+05:30
18	auth	0011_update_proxy_permissions	2026-09-07 14:29:04.536654+05:30
19	auth	0012_alter_user_first_name_max_length	2026-09-07 14:29:04.543126+05:30
20	sessions	0001_initial	2026-09-07 14:29:04.550234+05:30
21	app	0003_userprofile_password	2026-09-07 15:14:07.702163+05:30
22	app	0004_equipmentpms	2026-09-07 22:46:50.45368+05:30
23	app	0005_equipmentbreakdown	2026-09-08 00:28:56.146117+05:30
24	app	0006_remove_custodytransferlog_system_name_and_more	2026-09-11 16:04:06.845767+05:30
25	app	0007_deviceasset_device_type	2026-09-11 17:03:09.125054+05:30
26	app	0008_equipmentbreakdown_location	2026-09-15 14:51:45.193185+05:30
27	app	0009_alter_deviceasset_org_id_and_more	2026-09-16 12:10:37.081005+05:30
28	app	0010_deviceasset_assigned_designation	2026-09-21 16:15:23.898108+05:30
29	app	0011_alter_deviceasset_device_type	2026-09-22 11:25:51.980525+05:30
30	app	0012_deviceasset_assigned_email_and_more	2026-09-22 11:42:55.441357+05:30
31	app	0013_deviceasset_keyboard_spec_deviceasset_mouse_spec_and_more	2026-09-22 12:09:23.91751+05:30
32	app	0014_deviceasset_assigned_department	2026-09-22 12:28:12.622902+05:30
33	app	0015_deviceasset_brand_name	2026-09-23 10:33:06.51331+05:30
34	app	0016_deviceasset_anydesk_id_deviceasset_device_id	2026-09-23 11:22:20.792629+05:30
35	app	0017_alter_deviceasset_asset_id	2026-09-24 09:44:35.00169+05:30
36	app	0018_unify_workstation_asset_ids	2026-09-24 09:45:29.942947+05:30
37	app	0019_purge_live_data	2026-09-26 10:46:23.794704+05:30
38	app	0019_purge_all_live_data	2026-09-26 10:51:35.354667+05:30
39	app	0020_cleanup_auto_defaulted_brands	2026-09-26 12:17:34.050763+05:30
40	app	0021_cleanup_dummy_specs	2026-09-26 14:57:17.166346+05:30
41	app	0022_purge_legacy_m_asset_tags	2026-09-28 12:18:28.015438+05:30
42	app	0023_deduplicate_device_assets	2026-09-29 15:53:25.561336+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
7ukqfdbr96ypndnvmapark5u3a8w28q2	.eJxVjsFOxCAQhl9lM-dNA5S2S296NSYmPgAZYLbFpWCAHozx3Q3JWvX6fd8_mU_QuNdV74Wy9g5mEAzOf6FBe6PYjHvDuKTOplizN11Lurst3XNyFB7v7b8DK5YVZhjc1cqLoJEhWmku0qlJ9GJiZmCOSc4ZyUkocjSi4aOjYZzo2nNlFee9knAGdJuPOqRlIad9hLnmnX5wxI1ghlv2ZT29Y6VwLNobv_rAOYWGXj9Kpa2cHhr0pWasKR-Rj756DAVmeHqBr2_Km2Yw:1xA27A:0lTcAzPttmj-1ZZTQY_Bn7MBEwwyNaDP_WFp8yWaZxg	2026-10-09 14:51:08.342433+05:30
biq3crlbw3gfbj76trjhyjtmlgohsy1o	.eJxVjsFOxCAQhl9lM-dNA5S2S296NSYmPgAZYLbFpWCAHozx3Q3JWvX6fd8_mU_QuNdV74Wy9g5mEAzOf6FBe6PYjHvDuKTOplizN11Lurst3XNyFB7v7b8DK5YVZhjc1cqLoJEhWmku0qlJ9GJiZmCOSc4ZyUkocjSi4aOjYZzo2nNlFee9knAGdJuPOqRlIad9hLnmnX5wxI1ghlv2ZT29Y6VwLNobv_rAOYWGXj9Kpa2cHhr0pWasKR-Rj756DAVmeHqBr2_Km2Yw:1xA27A:0lTcAzPttmj-1ZZTQY_Bn7MBEwwyNaDP_WFp8yWaZxg	2026-10-09 14:51:08.488458+05:30
\.


--
-- Name: app_custodytransferlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_custodytransferlog_id_seq', 2, true);


--
-- Name: app_deviceasset_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_deviceasset_id_seq', 171, true);


--
-- Name: app_devicecomplaint_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_devicecomplaint_id_seq', 1, false);


--
-- Name: app_equipmentbreakdown_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_equipmentbreakdown_id_seq', 1, false);


--
-- Name: app_equipmentpms_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_equipmentpms_id_seq', 1, false);


--
-- Name: app_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.app_userprofile_id_seq', 24, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 24, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 42, true);


--
-- Name: app_custodytransferlog app_custodytransferlog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_custodytransferlog
    ADD CONSTRAINT app_custodytransferlog_pkey PRIMARY KEY (id);


--
-- Name: app_deviceasset app_deviceasset_dev_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_deviceasset
    ADD CONSTRAINT app_deviceasset_dev_id_key UNIQUE (dev_id);


--
-- Name: app_deviceasset app_deviceasset_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_deviceasset
    ADD CONSTRAINT app_deviceasset_pkey PRIMARY KEY (id);


--
-- Name: app_devicecomplaint app_devicecomplaint_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_devicecomplaint
    ADD CONSTRAINT app_devicecomplaint_pkey PRIMARY KEY (id);


--
-- Name: app_devicecomplaint app_devicecomplaint_ticket_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_devicecomplaint
    ADD CONSTRAINT app_devicecomplaint_ticket_id_key UNIQUE (ticket_id);


--
-- Name: app_equipmentbreakdown app_equipmentbreakdown_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_equipmentbreakdown
    ADD CONSTRAINT app_equipmentbreakdown_pkey PRIMARY KEY (id);


--
-- Name: app_equipmentpms app_equipmentpms_asset_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_equipmentpms
    ADD CONSTRAINT app_equipmentpms_asset_code_key UNIQUE (asset_code);


--
-- Name: app_equipmentpms app_equipmentpms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_equipmentpms
    ADD CONSTRAINT app_equipmentpms_pkey PRIMARY KEY (id);


--
-- Name: app_userprofile app_userprofile_emp_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_userprofile
    ADD CONSTRAINT app_userprofile_emp_id_key UNIQUE (emp_id);


--
-- Name: app_userprofile app_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_userprofile
    ADD CONSTRAINT app_userprofile_pkey PRIMARY KEY (id);


--
-- Name: app_userprofile app_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_userprofile
    ADD CONSTRAINT app_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: app_custodytransferlog_device_id_a0531503; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX app_custodytransferlog_device_id_a0531503 ON public.app_custodytransferlog USING btree (device_id);


--
-- Name: app_deviceasset_asset_id_6edf2886; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX app_deviceasset_asset_id_6edf2886 ON public.app_deviceasset USING btree (asset_id);


--
-- Name: app_deviceasset_asset_id_6edf2886_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX app_deviceasset_asset_id_6edf2886_like ON public.app_deviceasset USING btree (asset_id varchar_pattern_ops);


--
-- Name: app_deviceasset_dev_id_1e745957_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX app_deviceasset_dev_id_1e745957_like ON public.app_deviceasset USING btree (dev_id varchar_pattern_ops);


--
-- Name: app_devicecomplaint_ticket_id_50f6dfff_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX app_devicecomplaint_ticket_id_50f6dfff_like ON public.app_devicecomplaint USING btree (ticket_id varchar_pattern_ops);


--
-- Name: app_devicecomplaint_user_id_9ff854ed; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX app_devicecomplaint_user_id_9ff854ed ON public.app_devicecomplaint USING btree (user_id);


--
-- Name: app_equipmentpms_asset_code_02de92d4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX app_equipmentpms_asset_code_02de92d4_like ON public.app_equipmentpms USING btree (asset_code varchar_pattern_ops);


--
-- Name: app_userprofile_emp_id_56610d4c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX app_userprofile_emp_id_56610d4c_like ON public.app_userprofile USING btree (emp_id varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: app_custodytransferlog app_custodytransferlog_device_id_a0531503_fk_app_deviceasset_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_custodytransferlog
    ADD CONSTRAINT app_custodytransferlog_device_id_a0531503_fk_app_deviceasset_id FOREIGN KEY (device_id) REFERENCES public.app_deviceasset(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_devicecomplaint app_devicecomplaint_user_id_9ff854ed_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_devicecomplaint
    ADD CONSTRAINT app_devicecomplaint_user_id_9ff854ed_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: app_userprofile app_userprofile_user_id_370bd89d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_userprofile
    ADD CONSTRAINT app_userprofile_user_id_370bd89d_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict Lg0nUpnU5Fomi3Z7m3iOJdixp66O3B44Ij6P04HZOXlWtxd3gCkYfRZoPG7axND

