# Generated by Django 6.1 on 2026-09-02 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=30, unique=True)),
                ('user_full_name', models.CharField(max_length=150)),
                ('emp_id', models.CharField(blank=True, max_length=50)),
                ('user_email', models.CharField(blank=True, max_length=150)),
                ('user_dept', models.CharField(blank=True, max_length=100)),
                ('org_id', models.CharField(choices=[('UNI', 'ABC University'), ('HOSP', 'ABC Hospital')], default='UNI', max_length=20)),
                ('device_asset_id', models.CharField(max_length=50)),
                ('system_name', models.CharField(max_length=100)),
                ('room_location', models.CharField(blank=True, max_length=100)),
                ('issue_category', models.CharField(choices=[('Hardware Fault', 'Hardware Fault (CPU / Motherboard / RAM / PSU)'), ('Display & Screen', 'Display / Monitor Flickering / No Signal'), ('Network & Internet', 'Network Drop / Ethernet / Wi-Fi Disconnect'), ('OS & Software Crash', 'Operating System Crash / Blue Screen / Freezing'), ('Peripherals Damage', 'Damaged Keyboard / Mouse / Accessories'), ('Location Relocation', 'Request Physical Shift to Another Lab/Ward'), ('Other Issue', 'Other Technical Issue')], default='Hardware Fault', max_length=100)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High Priority'), ('Critical', 'Critical / Emergency')], default='Normal', max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('In Progress', 'In Progress / Assigned'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=30)),
                ('admin_remarks', models.TextField(blank=True, default='')),
                ('technician_name', models.CharField(blank=True, default='IT Desk Team', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('org_id', models.CharField(choices=[('UNI', 'ABC University'), ('HOSP', 'ABC Hospital')], default='UNI', max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('assigned_asset_id', models.CharField(blank=True, help_text='e.g. IT-PC-00125 or HOSP-ICU-00042', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
