# Generated by Django 6.1 on 2026-09-07 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.CharField(help_text='e.g. dev-01', max_length=50, unique=True)),
                ('asset_id', models.CharField(help_text='e.g. IT-PC-00125', max_length=50, unique=True)),
                ('system_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('org_id', models.CharField(choices=[('UNI', 'ABC University'), ('HOSP', 'ABC Hospital')], default='UNI', max_length=20)),
                ('org_name', models.CharField(blank=True, max_length=100)),
                ('building_name', models.CharField(blank=True, max_length=100)),
                ('floor_name', models.CharField(blank=True, max_length=100)),
                ('room_name', models.CharField(blank=True, max_length=100)),
                ('assigned_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_user_name', models.CharField(blank=True, default='Unassigned', max_length=150)),
                ('assigned_emp_id', models.CharField(blank=True, max_length=50)),
                ('monitor_spec', models.CharField(blank=True, max_length=255)),
                ('cpu_processor', models.CharField(blank=True, max_length=255)),
                ('storage_ram', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.CharField(blank=True, max_length=50)),
                ('warranty_expiry_date', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Maintenance', 'In Maintenance'), ('Decommissioned', 'Decommissioned')], default='Active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_id'],
            },
        ),
        migrations.CreateModel(
            name='CustodyTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_asset_id', models.CharField(max_length=50)),
                ('system_name', models.CharField(max_length=100)),
                ('from_user_name', models.CharField(default='Unassigned', max_length=150)),
                ('from_emp_id', models.CharField(blank=True, max_length=50)),
                ('to_user_name', models.CharField(max_length=150)),
                ('to_emp_id', models.CharField(blank=True, max_length=50)),
                ('handover_date', models.CharField(max_length=50)),
                ('assigned_by', models.CharField(default='IT Admin Desk', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custody_logs', to='app.deviceasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
