# Generated by Django 6.1 on 2026-09-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_deviceasset_custodytransferlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Staff portal account password', max_length=150),
        ),
    ]
