# Generated by Django 6.1 on 2026-09-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(default='Computer', help_text='e.g. Computer, ICU Monitor, Laptop', max_length=150)),
                ('company_name', models.CharField(default='HP', help_text='e.g. HP, Dell, Lenovo, GE Healthcare', max_length=100)),
                ('installation_date', models.CharField(default='08-11-2021', help_text='Installation Date (DD-MM-YYYY)', max_length=50)),
                ('asset_code', models.CharField(help_text='e.g. KH/IT/COMPUTER/1', max_length=100, unique=True)),
                ('maintenance_frequency', models.CharField(choices=[('QUARTERLY', 'Quarterly (Every 3 Months)'), ('HALF-YEARLY', 'Half-Yearly (Every 6 Months)'), ('ANNUALLY', 'Annually (Once a Year)'), ('MONTHLY', 'Monthly (Every Month)')], default='QUARTERLY', max_length=50)),
                ('pms1_done_date', models.CharField(default='08-08-2022', help_text='1st PMS Done Date', max_length=50)),
                ('pms2_due_date', models.CharField(default='08-11-2022', help_text='Due Date of 2nd PMS', max_length=50)),
                ('pms2_done_date', models.CharField(default='09-11-2022', help_text='2nd PMS Done Date', max_length=50)),
                ('pms3_due_date', models.CharField(default='09-02-2023', help_text='Due Date of 3rd PMS', max_length=50)),
                ('pms3_done_date', models.CharField(default='09-02-2023', help_text='3rd PMS Done Date', max_length=50)),
                ('pms4_due_date', models.CharField(default='09-05-2023', help_text='Due Date of 4th PMS', max_length=50)),
                ('pms4_done_date', models.CharField(blank=True, default='', help_text='4th PMS Done Date (if completed)', max_length=50)),
                ('status', models.CharField(choices=[('Completed', 'All Cycles Completed'), ('Pending 4th PMS', 'Pending 4th PMS'), ('Due Soon', 'Upcoming Due'), ('Overdue', 'Service Overdue')], default='Pending 4th PMS', max_length=50)),
                ('department_location', models.CharField(blank=True, default='IT Lab 101', max_length=150)),
                ('engineer_notes', models.TextField(blank=True, default='Quarterly system fan blow-out, thermal paste check, power supply testing and OS health diagnostic completed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment PMS Record',
                'verbose_name_plural': 'Equipment PMS Records',
                'ordering': ['id'],
            },
        ),
    ]
