# Generated by Django 6.1 on 2026-09-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_equipmentpms'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown_date', models.CharField(default='26.07.2022', help_text='e.g. 26.07.2022 or 02-09-2026', max_length=50)),
                ('breakdown_time', models.CharField(default='2.00 pm', help_text='e.g. 2.00 pm or 14:30', max_length=50)),
                ('asset_id', models.CharField(default='IT-PC-00101', help_text='e.g. IT-PC-00101 or Asset Code', max_length=100)),
                ('device_name', models.CharField(choices=[('Monitor', 'Monitor'), ('CPU', 'CPU'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('UPS', 'UPS'), ('Laser Printer', 'Laser Printer'), ('Barcode Printer', 'Barcode Printer'), ('Scanner', 'Scanner'), ('Other', 'Other')], default='CPU', help_text='IT Device Name', max_length=100)),
                ('breakdown_cause', models.TextField(default='Hardware malfunction', help_text='Breakdown Cause / Issue description')),
                ('equipment_type', models.CharField(choices=[('Critical', 'Critical'), ('Routine', 'Routine')], default='Routine', help_text='Critical or Routine', max_length=50)),
                ('intimation_datetime', models.CharField(default='26.07.2022 2.10 pm', help_text='Intimation date & time to IT CELL', max_length=100)),
                ('checkin_datetime', models.CharField(default='26.07.2022 2.20 pm', help_text='IT CELL Checkin Date & Time', max_length=100)),
                ('dept_hod_name', models.CharField(blank=True, default='Dr. Rajesh Sharma', help_text='Name of Departmental HOD', max_length=150)),
                ('it_staff_name', models.CharField(blank=True, default='Er. Amit Verma (IT CELL)', help_text='Name of IT CELL / BME staff', max_length=150)),
                ('repair_datetime', models.CharField(blank=True, default='26.07.2022 2.35 pm', help_text='Repair Date & Time', max_length=100)),
                ('tat_duration', models.CharField(blank=True, default='35 minutes', help_text='Total Turn Around Time (TAT)', max_length=100)),
                ('sign_dept_hod', models.CharField(blank=True, default='Dr. Rajesh Sharma (Verified)', help_text='Sign of Departmental HOD', max_length=150)),
                ('sign_it_cell', models.CharField(blank=True, default='Er. Amit Verma (IT CELL)', help_text='Sign of IT CELL', max_length=150)),
                ('status', models.CharField(choices=[('Resolved', 'Resolved (Repaired)'), ('Under Repair', 'Under Active Repair'), ('Pending Review', 'Pending Department Review')], default='Resolved', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment Breakdown',
                'verbose_name_plural': 'Equipment Breakdowns',
                'ordering': ['-id'],
            },
        ),
    ]
