# Generated by Django 6.1 on 2026-09-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_equipmentbreakdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custodytransferlog',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='deviceasset',
            name='system_name',
        ),
        migrations.RemoveField(
            model_name='devicecomplaint',
            name='system_name',
        ),
        migrations.AlterField(
            model_name='deviceasset',
            name='org_id',
            field=models.CharField(choices=[('UNI', 'ABC University'), ('HOSP', 'PSM Hospital')], default='UNI', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicecomplaint',
            name='org_id',
            field=models.CharField(choices=[('UNI', 'ABC University'), ('HOSP', 'PSM Hospital')], default='UNI', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='breakdown_date',
            field=models.CharField(default='26/07/2022', help_text='e.g. 26/07/2022 or 02/09/2026', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='breakdown_time',
            field=models.CharField(default='2:00 pm', help_text='e.g. 2:00 pm or 14:30', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='checkin_datetime',
            field=models.CharField(default='26/07/2022 2:20 pm', help_text='IT CELL Checkin Date & Time', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='intimation_datetime',
            field=models.CharField(default='26/07/2022 2:10 pm', help_text='Intimation date & time to IT CELL', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='repair_datetime',
            field=models.CharField(blank=True, default='26/07/2022 2:35 pm', help_text='Repair Date & Time', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='org_id',
            field=models.CharField(choices=[('UNI', 'ABC University'), ('HOSP', 'PSM Hospital')], default='UNI', max_length=20),
        ),
    ]
