# Generated by Django 6.1 on 2026-09-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_custodytransferlog_system_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceasset',
            name='device_type',
            field=models.CharField(blank=True, default='CPU', help_text='e.g. CPU, Display, Keyboard, Mouse, Printer', max_length=50),
        ),
    ]
