# Generated by Django 6.1 on 2026-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_deviceasset_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbreakdown',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Department / Room / Location', max_length=150),
        ),
    ]
