# Generated by Django 6.1 on 2026-09-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_equipmentbreakdown_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceasset',
            name='org_id',
            field=models.CharField(choices=[('UNI', 'Swaminarayan University'), ('HOSP', 'PSM Hospital')], default='UNI', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicecomplaint',
            name='org_id',
            field=models.CharField(choices=[('UNI', 'Swaminarayan University'), ('HOSP', 'PSM Hospital')], default='UNI', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='org_id',
            field=models.CharField(choices=[('UNI', 'Swaminarayan University'), ('HOSP', 'PSM Hospital')], default='UNI', max_length=20),
        ),
    ]
