# Generated by Django 6.1 on 2026-09-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_deviceasset_org_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceasset',
            name='assigned_designation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
