# Generated by Django 6.1 on 2026-09-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_deviceasset_assigned_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceasset',
            name='device_type',
            field=models.CharField(blank=True, default='CPU', help_text='e.g. CPU, Display, Keyboard, Mouse, Printer', max_length=100),
        ),
    ]
