# Generated by Django 6.1 on 2026-09-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_deviceasset_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceasset',
            name='assigned_email',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='deviceasset',
            name='assigned_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
