# Generated by Django 6.1 on 2026-09-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_deviceasset_assigned_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceasset',
            name='keyboard_spec',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deviceasset',
            name='mouse_spec',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deviceasset',
            name='printer_spec',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deviceasset',
            name='tablet_spec',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deviceasset',
            name='ups_spec',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
