# Generated by Django 6.1 on 2026-09-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_deviceasset_assigned_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceasset',
            name='brand_name',
            field=models.CharField(blank=True, default='', help_text='e.g. Dell, HP, Lenovo, Logitech, Zebra, APC, Samsung', max_length=100),
        ),
    ]
