# Generated by Django 6.1 on 2026-09-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_deviceasset_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceasset',
            name='anydesk_id',
            field=models.CharField(blank=True, default='', help_text='AnyDesk Remote ID', max_length=100),
        ),
        migrations.AddField(
            model_name='deviceasset',
            name='device_id',
            field=models.CharField(blank=True, default='', help_text='Hardware / Tablet Device ID', max_length=100),
        ),
    ]
