# Generated by Django 6.1 on 2026-09-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_deviceasset_anydesk_id_deviceasset_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceasset',
            name='asset_id',
            field=models.CharField(db_index=True, help_text='e.g. IT-PC-00125', max_length=50),
        ),
    ]
