# Generated by Django on 2026-09-24
from django.db import migrations
from collections import defaultdict


def unify_workstation_asset_ids(apps, schema_editor):
    DeviceAsset = apps.get_model('app', 'DeviceAsset')
    groups = defaultdict(list)
    for d in DeviceAsset.objects.all().order_by('id'):
        name = (d.assigned_user_name or '').strip().lower()
        if name and 'unassigned' not in name:
            groups[name].append(d)

    for name, devs in groups.items():
        if len(devs) > 1:
            base_tag = devs[0].asset_id
            for dev in devs[1:]:
                if dev.asset_id != base_tag:
                    dev.asset_id = base_tag
                    dev.save(update_fields=['asset_id'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_deviceasset_asset_id'),
    ]

    operations = [
        migrations.RunPython(unify_workstation_asset_ids, reverse_noop),
    ]
