# Generated by Django 6.1 on 2026-10-05 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_lock_radheshyam_pharmacy_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbreakdown',
            name='ticket_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Linked Helpdesk Ticket ID', max_length=50),
        ),
        migrations.CreateModel(
            name='ITTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name of IT Technician', max_length=150, unique=True)),
                ('emp_id', models.CharField(blank=True, help_text='Employee / Staff ID', max_length=50)),
                ('role_title', models.CharField(default='Hardware & Systems Engineer', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(default='Hardware, Peripherals & OS', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IT Technician',
                'verbose_name_plural': 'IT Technicians',
                'ordering': ['name'],
            },
        ),
    ]
