# Generated by Django 6.1 on 2026-10-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_equipmentbreakdown_ticket_id_ittechnician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='dept_hod_name',
            field=models.CharField(blank=True, default='Department Incharge', help_text='Name of Departmental HOD', max_length=150),
        ),
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='it_staff_name',
            field=models.CharField(blank=True, default='IT Support Desk', help_text='Name of IT CELL / BME staff', max_length=150),
        ),
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='sign_dept_hod',
            field=models.CharField(blank=True, default='Department Incharge (Verified)', help_text='Sign of Departmental HOD', max_length=150),
        ),
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='sign_it_cell',
            field=models.CharField(blank=True, default='IT Support Desk', help_text='Sign of IT CELL', max_length=150),
        ),
    ]
